(require 'hl-line)
(set-foreground-color "yellow")
(set-background-color "dark blue")

(set-face-foreground 'font-lock-builtin-face "red")
(set-face-foreground 'font-lock-comment-delimiter-face "grey45")
(set-face-foreground 'font-lock-comment-face "grey45")
(set-face-foreground 'font-lock-constant-face "green")
(set-face-foreground 'font-lock-doc-face "grey45")
(set-face-foreground 'font-lock-function-name-face "lightgreen")
(set-face-foreground 'font-lock-keyword-face "lightblue")
(set-face-foreground 'font-lock-negation-char-face "grey65")
(set-face-foreground 'font-lock-preprocessor-face "grey65")
(set-face-foreground 'font-lock-regexp-grouping-backslash "red")
(set-face-foreground 'font-lock-regexp-grouping-construct "red")
(set-face-foreground 'font-lock-string-face "cyan")
(set-face-foreground 'font-lock-type-face "white")
(set-face-foreground 'font-lock-variable-name-face "green")
(set-face-foreground 'font-lock-warning-face "grey65")

(set-face-background 'hl-line "grey25")
